language: ruby
cache: bundler
rvm:
- 2.1.2
branches:
  only:
  - master
install: bundle install
script: bundle exec rake test
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  provider: s3
  access_key_id: AKIAJHG4Y77ILSJMBNMQ
  secret_access_key:
    secure: QB+h2Xi+6H0yehDKaCpq02KJF7iEaT6zmZrfrfi9Owr0WDNW4kBzKWdvV4lm+nK1I7nuuBBECDcl8xWJRm8baTdE8fxU6o7gyWXXa8v90RHVumY2M+VsI8lYPLdaSyhUnztC0pB6WX3NJKGA0lBNOga/OPEGKPSLxq4JxTF3/Ln8O0gRmvKYVmrs5Pyc6r9t68jOHxlFwwpxYWT06fZcxPpYEtHYukvi704LRYGFonp3H07RNkS/1uue87w6PZZGPgeGdgxiMPyAkqeNzz9n3U5p7+p3BlFyyrxAC8Rzmj8GlTuDGbNlit03Z5YvRPXntfSIHpFYBdCCQr3msz7X9mExKoA0ICZXLNVtZOdIaA1fNqzXLBqo3MOPTe2M0ziDMi4f9qaKR02HXTe0TYpRhuUZJQQvktx/is2mCQc2ZKWTvne2U/KcGciaTPY5HJfotoKlmEJRI9FU7hck31108LYn+cFWIGAE74u8nQlUy1xU2BYhidMvEgD6XWhpigzLtDXJIfYmpV1KE27vTAWZqv1N17ZdfbpsxGcxI+bNa7PsUlZ4Wr9YMVojc+50KL57f/6MPx2Fom9Jb0zcz72A9S0uWcIprwhe3rE/dF/GbW05beEYuDUW0VabG9XfmLmgLujE5TtmHr7L9wxZP+bG+nSB2mYroOPOnBdXNe1qtp8=
  bucket: documentatie.uitdatabank.be
  region: eu-west-1
  skip_cleanup: true
  local_dir: _site
  on:
    branch: master
    repo: cultuurnet/uit-documentatie
